"""
Schema exports.
"""
from app.schemas.auth import (
    UserRegisterRequest,
    LoginRequest,
    EmailVerificationRequest,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    ResendOTPRequest,
    OAuthCallbackRequest,
    TokenResponse,
    UserResponse,
    CustomerResponse,
    AdminResponse,
    OAuthLoginResponse,
    MessageResponse,
    OAuthProviderResponse,
    OAuthProvidersResponse,
)
from app.schemas.role import (
    RoleCreateRequest,
    RoleUpdateRequest,
    PermissionCreateRequest,
    AssignRoleRequest,
    OverridePermissionsRequest,
    PermissionResponse,
    RoleResponse,
    RoleDetailResponse,
    RoleListItemResponse,
    RolesListResponse,
    PermissionsListResponse,
)
from app.schemas.response import (
    ErrorDetail,
    ErrorResponse,
    ValidationErrorResponse,
    SuccessResponse,
    PaginatedResponse,
    ErrorCode,
    create_error_response,
    create_validation_error_response,
    create_success_response,
)

__all__ = [
    # Auth schemas
    "UserRegisterRequest",
    "LoginRequest",
    "EmailVerificationRequest",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "ResendOTPRequest",
    "OAuthCallbackRequest",
    "TokenResponse",
    "UserResponse",
    "CustomerResponse",
    "AdminResponse",
    "OAuthLoginResponse",
    "MessageResponse",
    "OAuthProviderResponse",
    "OAuthProvidersResponse",
    # Role schemas
    "RoleCreateRequest",
    "RoleUpdateRequest",
    "PermissionCreateRequest",
    "AssignRoleRequest",
    "OverridePermissionsRequest",
    "PermissionResponse",
    "RoleResponse",
    "RoleDetailResponse",
    "RoleListItemResponse",
    "RolesListResponse",
    "PermissionsListResponse",
    # Response schemas
    "ErrorDetail",
    "ErrorResponse",
    "ValidationErrorResponse",
    "SuccessResponse",
    "PaginatedResponse",
    "ErrorCode",
    "create_error_response",
    "create_validation_error_response",
    "create_success_response",
    "ResponseModel",  # Backward compatibility
]
